name: Install nginx

on:
  push:
    branches:
    - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Install nginx
        run: sudo apt update && sudo apt install -y nginx && sudo systemctl start nginx
      - run: echo "nginx has been installed"
      - name: Curl install
        run: sudo apt install -y curl && curl --version
      - run: |
          curl localhost > nc_rep.log 2>&1
          ls -la
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: nc_rep.log

